config/routes.rb
AuditFace::Application.routes.draw do
  
  resources :reports

  resources :activities, only: [:index]

  devise_for :users 

  get "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_findings"
  resources :dashboards
  get "audits/export_findings"
  post "audits/export_findings"
  get "audits/share_schedule"
  post "audits/share_schedule"
  get "audits/find_capa"
  post "audits/find_capa"
  resources :audits do
  resources :findings
  
  end
 resources :findings
  resources :search

  
  root :to => "pages#landing"
  
  get "/pages/*id" => 'pages#show', as: :page, format: false
  get 'pages/landing' => 'high_voltage/pages#show', id: 'landing'

  get "/pages2/*id" => 'pages2#show', as: :page, format: false
  get 'pages2/landing2' => 'high_voltage/pages2#show', id: 'landing2'

end

app/models/audit.rb
class Audit < ActiveRecord::Base
  attr_accessible :auditee_email, :auditee_name, :auditor_email, :auditor_name, :department_name, :end_date, :start_date, :user_id, :audit_type,:location, :secondry_auditor_name, :secondry_auditor_email
  belongs_to :user
  has_many :findings, :dependent => :destroy
  
  validates :department_name, :auditee_name, :auditee_email, :auditor_name, 
            :auditor_email, :location, :presence => true
            
  validates :start_date, :date => {:before_or_equal_to => :end_date, :message => 'must be before or same as end date' }
  
  self.per_page = 3

  validate :cannot_audit_self

  def cannot_audit_self
    self.errors[:base] << "You can not audit yourself." if self.auditee_email == self.auditor_email
  end
  def self.capa_pending_auto_follow_up
    @audits_capa_pending = []
    @audits = Audit.all
    @audits.each do |audit|
      audit.findings.each do |finding|
        if finding.status_id == "CAPA Pending" || finding.status_id == ""
          @audits_capa_pending << audit
          break
        end
      end
    end
    @audits_capa_pending.each do |audit|
      UserMailer.capa_pending_auto_follow_up(audit,current_user).deliver
    end
     #@user = User.all
     # @user.each do |u|
     #   UsersMailer.weekly_mail(u).deliver
    #end
  end
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
     before_filter :check_audit_status, :only => [:edit,:update]
      require 'prawn'
  # GET /audits
  # GET /audits.json
  def index
    @audits_not_started = current_user.audits.where('start_date > ?',Time.now)      
    @audits= current_user.audits.paginate(:page => params[:page], :per_page => 3).order('id DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @audits }
    end

  end

  # GET /audits/1
  # GET /audits/1.json
  def show
    @audit = current_user.audits.find(params[:id])
    @findings= @audit.findings.paginate(:page => params[:page], :per_page => 7).order('id DESC')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @audit }
     
    end
  end

  # GET /audits/new
  # GET /audits/new.json
  def new
    @audit = current_user.audits.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @audit }
    end
  end

  # GET /audits/1/edit
  def edit
    @audit = current_user.audits.find(params[:id])
    
  end

  # POST /audits
  # POST /audits.json
  def create
    @audit = current_user.audits.new(params[:audit])
    audit = params[:audit]
    start_date = DateTime.new(params["audit"]["start_date(1i)"].to_i, params["audit"]["start_date(2i)"].to_i,params["audit"]["start_date(3i)"].to_i,
                                                                    params["audit"]["start_date(4i)"].to_i,params["audit"]["start_date(5i)"].to_i)
    
    end_date = DateTime.new(params["audit"]["end_date(1i)"].to_i, params["audit"]["end_date(2i)"].to_i,params["audit"]["end_date(3i)"].to_i,
                                                                    params["audit"]["end_date(4i)"].to_i,params["audit"]["end_date(5i)"].to_i)
     @all_audits = Audit.where("auditor_email = ? or auditee_email = ?",params[:audit][:auditor_email], params[:audit][:auditee_email])
    
      @all_audits.each do |audit|
             if (audit.start_date.to_i..audit.end_date.to_i).include?(start_date.to_i||end_date.to_i)
               @audit.errors[:base] << "Auditor or auditee is already assigned, please select another date "
                 break
             end
         end
    
    respond_to do |format|
       if @audit.errors.any?
            format.html { render action: "new" }
            format.json { render json: @audit.errors, status: :unprocessable_entity }
       elsif @audit.save
         UserMailer.assign_audit(@audit,@audit.auditor_email,current_user).deliver
         UserMailer.assign_auditee(@audit,@audit.auditee_email,current_user).deliver
        format.html { redirect_to audits_path, notice: 'Audit was successfully created.' }
        format.json { render json: @audit, status: :created, location: @audit }
      else
        format.html { render action: "new" }
        format.json { render json: @audit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /audits/1
  # PUT /audits/1.json
  def update
    @audit = current_user.audits.find(params[:id])
  
    if @audit.auditor_email != params[:audit][:auditor_email]
       UserMailer.audit_deleted_auditor(@audit,current_user).deliver
       UserMailer.assign_audit(@audit,params[:audit][:auditor_email],current_user).deliver       
    end  
    if @audit.auditee_email != params[:audit][:auditee_email]
      UserMailer.audit_deleted_auditee(@audit,current_user).deliver     
      UserMailer.assign_auditee(@audit,params[:audit][:auditee_email],current_user).deliver
    end  
    respond_to do |format|
      if @audit.update_attributes(params[:audit])
        format.html { redirect_to audits_path, notice: 'Audit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @audit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audits/1
  # DELETE /audits/1.json
  def destroy
 
    @audit = current_user.audits.find(params[:id])
    @audit.destroy
    
    UserMailer.audit_deleted_auditor(@audit,current_user).deliver
    UserMailer.audit_deleted_auditee(@audit,current_user).deliver
    respond_to do |format|
      format.html { redirect_to audits_url }
      format.json { head :no_content }
    end
  end
  
  def export_findings
    audit = current_user.audits.find(params[:audit_id].to_i)
   
# # item = Consolidation.find_all_by_customer_id_and_status(params[:customer_id],true).map do |item|
# # [
# # item.settlement_date.strftime("%m/%d/%Y"),
# # item.settlement_amount,
# # item.ach_conf_code,
# # ]
# # end
# item.unshift(["Date","Settlement Amount","ACH Reference"])
    pdf = Prawn::Document.new 
    pdf.font_size 8 
    number=0
    point = -50
 #   pdf.bounding_box pdf.bounds.top_left, :width => 500 do
    
       pdf.bounding_box [point+50, pdf.cursor+10], :width => 500  do
         pdf.transparent(1.0) {pdf.stroke_bounds }
         #pdf.total_left_padding 10                
         pdf.move_down 5
       #pdf.pad(60) do 
         #  pdf.text.margin 0.5
        # pdf.margin_left (10) do
         pdf.text "Department Name :"+ audit.department_name if audit.department_name
         pdf.move_down 5
         pdf.text "Created On: " + audit.created_at.strftime("%d-%m-%y")
         pdf.move_down 5
         pdf.text "Audit Rating : " + "No Rating"
         pdf.move_down 5
         pdf.text "Start date: : " + audit.start_date.strftime("%d-%m-%y") if audit.start_date
         pdf.move_down 5
         pdf.text "End date:  : " + audit.end_date.strftime("%d-%m-%y") if audit.end_date
         pdf.move_down 5
         pdf.text "Auditor : " + audit.auditor_name
         pdf.move_down 5
         pdf.text "Auditee : " + audit.auditee_name
         pdf.move_down 5
         pdf.text "Location : " + audit.location.to_s
         pdf.move_down 5
         pdf.text "Status : " + ""
        
        pdf.transparent(1.0) {pdf.stroke_bounds }
        pdf.move_down 30
       #end
      end

    audit.findings.each do |finding|
       pdf.text "Finding #{number += 1}"  
       pdf.move_down 10
       pdf.bounding_box [point+50, pdf.cursor+1], :width => 500,:padding => 50  do
        pdf.stroke_bounds 
        pdf.move_down 5
        pdf.text "Observation: " + finding.description if finding.description
        pdf.move_down 5
        pdf.text "Corrective Action : " + finding.corrective_action if finding.corrective_action
        pdf.move_down 5
        pdf.text "Preventive Action : " + finding.preventive_action if finding.preventive_action
        pdf.move_down 5
        pdf.text "Risk Rating : " + finding.risk_rating if finding.risk_rating
        pdf.move_down 5 
        pdf.text "Status : " + finding.status_id if finding.status_id
        pdf.move_down 5
         pdf.text "Closed On : " + ""
        pdf.move_down 10
        #pdf.stroke_bounds 
        pdf.stroke_bounds 
        pdf.move_down 30
    end  
    end

     
  #  end
    
      filename = File.join(Rails.root, "/public", "findings.pdf")
      pdf.render_file filename
      
      send_data pdf.render, :filename => "findings.pdf", :type => "application/pdf"
   end
  
  def share_schedule
    emails = params[:email].split(',')
    emails.each do |email|
      puts "#{email}"
      UserMailer.share_audit_schedule(email,current_user).deliver
    end
    
    redirect_to audits_path,:notice => "Audit Schedule shared."
  end
  def find_capa
    @capa = Finding.find(params[:finding_id]).corrective_action
    respond_to do |format|
     # format.html # show.html.erb
     format.json { render json:  @capa.to_json }
    end
  end
  private
      def check_audit_status
        audit = current_user.audits.find(params[:id])
        if  !(audit.start_date.to_i > Time.now.to_i)
          redirect_to "/404.html"
          
        end
      end
 end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/views/audits/edit.html.erb
<%= render 'form' %>

app/views/audits/index.html.erb
   
   
   <div class="container">
    <div class="row-fluid">
    <div class="col-lg-12 col-lg-offset-1">
    <%= link_to 'New Audit', new_audit_path, class: "btn btn-default btn-sm" %>
   <!-- <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" > Import Findings (Coming Soon) </button>-->

      
     <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal1"> Preview Schedule </button>
    
    </div>
    </div>
    </div>
     <br/>
   <% @audits.each do |audit| %>
   <div class="container">
   <div class="row-fluid">
   <div class="col-lg-6 col-md-6 col-lg-offset-1">
   
    <small>
      <div class="panel panel-default" >
      <% audit.findings.each do |finding| %>  
        <%if finding.status_id != "Closed"%>
          <% break %>
        <%end %>  
      <% end  %>
      <%#= (audit.start_date..audit.end_date).cover?(Time.now)%>
      
          <div class="panel-heading" style="background:#ecf0f1">
              <span class="label label-default">Audit   # <%= audit.id %></span> | <strong style="font-size:14px;"><%= audit.department_name %></strong>
                
                <span class="label label-success pull-right">
               <%if (audit.start_date.to_i..audit.end_date.to_i).include?(Time.now.to_i) %>
          
            <%= "In Progress" %> 
            <%elsif audit.start_date.to_i > Time.now.to_i %>
              <%= "Not Started"%>
            <%elsif Time.now.to_i > audit.end_date.to_i   %>  
              <%= "Audit Completed" %>
          <%end%> 
      </span>
      </div>
      <div class="panel-body" style="background:#ecf0f1">
        <strong>Auditor: </strong> <%= audit.auditor_name %> | <strong>Auditee: </strong><%= audit.auditee_name %>
      </div>

            <div class="panel-footer" style="background:#ecf0f1">  
                    <div class="meta">
                   <p>
                   <%= time_ago_in_words(audit.created_at) + " ago" %>    |

                     <% if audit.start_date.to_i > Time.now.to_i %>
                     <%= link_to " Modify", edit_audit_path(audit), class: "btn" %>  | 
                     <i class="fa fa-trash-o fa-lg"></i> <%= link_to " Delete", audit, class: "btn", method: :delete, data: { Confirm: "Are you sure"} %> |
                      <%= link_to " View Finding", audit, class: "btn btn-link btn-sm disabled" %>
                    <i class="fa fa-share-square-o fa-lg"></i>
                      <%= link_to " Add Finding", new_audit_finding_path(audit.id), class: "btn btn-primary btn-sm pull-right disabled" %>  
                    <% else %>  
                     <%= link_to " Modify", edit_audit_path(audit), class: "btn disabled" %>  |
                     <i class="fa fa-trash-o fa-lg"></i> <%= link_to " Delete", audit, class: "btn disabled", method: :delete, data: { Confirm: "Are you sure"} %> |
                      <%= link_to " View Finding", audit, class: "btn btn-link btn-sm" %>
                    <i class="fa fa-share-square-o fa-lg"></i>
                      <%= link_to " Add Finding", new_audit_finding_path(audit.id), class: "btn btn-default btn-sm pull-right" %>  
                    <%end%>  
                     </p>
                         
                     </div>
                     </div>
               </div> 
    <div class="page-header"></div>
        </div>


    </small>

 </div>

 </div>

 </div>
    <% end %>
   
<div class="container">
    <div class="row-fluid"> 
    <div class="col-lg-12 col-lg-offset-1">
    <%= will_paginate @audits %>
    </div>
    </div>
    </div>




<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload findings to audits</h4>
      </div>
      <div class="modal-body">
     <form class="form-horizontal" role="form">
     <div class="form-group">
        <div class="col-sm-8">
            <select class="form-control">
            <option>Select Audit</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            </select>
       </div>
       <br/><br/><br/>
        
        <div class="col-sm-8">
        
        <button type="button" class="btn btn-info btn-block">Download template</button>
        </div>
      <br/><br/><br/>
         <div class="col-sm-8">

        <button type="button" class="btn btn-success btn-block">Import</button>
        </div>
         <br/><br/><br/>
        <div class="col-sm-12">
       
       <ul>
           <li> Upload finding in provided template only</li>
           <li> Avoid blank rows and duplicate import</li>
           <li> File import will only accept "Critical, High, Medium and Low" risk categories. Finding will skip if incorrect risk category is entered</li>
           <li> Ensure audits do not contain any findings before an import is made </li>
           <li> Finding import can be used only once. Import will only perform "add finding" action</li>
           <li> To modify a finding , an user must visit the finding in application</li>
           
       </ul>
        </div>
 
     </div>
    
     </form>
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<%= simple_form_for("", :url => url_for(:controller => 'audits', :action => 'share_schedule')) do |f| %>
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Preview and Share audit schedule</h4>
      </div>
      <div class="modal-body">
       

        <small>
      <table class="table table-hover table-responsive table-condensed">
            <thead>
		
            <tr style="background:#ecf0f1">
		        <th> Audit ID</th>
		        <th>Department</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Auditor</th>
            <th>Auditee</th>
            <th>Location</th>
 	          </tr>
            </thead>
        
        <tbody>
          <% @audits_not_started.each do |audit| %>
        <tr>
		    <td> <%= audit.id %> </td>
        <td><%= audit.department_name %></td>
        
        <td><%= audit.start_date.strftime("%d-%m-%y")%></td>
        <td><%= audit.end_date.strftime("%d-%m-%y")%></td>
		    <td><%= audit.auditor_name%></td>
        <td><%= audit.auditee_name%></td>
        <td><%= audit.location%></td>
        </tr>
        <%end%>
	    
        </tbody>
       
        
      </table>
          
      </small>
        <%= f.text_field :email, :class => 'form-control',:id=>"inputEmail3",:placeholder=>"Email address, seperate by comma to enter multiple email address" %>
      </div>
      
      
      <div class="modal-footer">
          <%= f.button :submit,"Share", :class => 'btn btn-primary' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<% end %>

app/views/audits/new.html.erb
<%= render 'form' %>

app/views/audits/show.html.erb
   

    <div class="container">
    <div class="row-fluid">
    <div class="col-lg-9 col-md-9 col-lg-offset-1">
       <%= link_to "Create Findings", new_audit_finding_path(@audit.id), class: "btn btn-default btn-sm" %> 
      <%= link_to "Export Findings", "export_findings?audit_id=#{@audit.id}", class: "btn btn-info btn-sm" %>
      <label class="pull-right"> <input type="checkbox"> Findings submitted        </label>
     
    </div>
        
    </div>
    </div>
    <br/>
    
    <div class="container">
    <div class="row-fluid">
    <div class="col-lg-10 col-md-10 col-lg-offset-1">
        
    
          <%#=  @audit.findings %>
          <%= will_paginate @findings %>
              <% if @audit.findings!= [] %>  
            
              <% @findings.each do |finding| %>
                  <small>
                  <div class="panel panel-default">
                       <div class="panel-heading" style="background:#ecf0f1">
                         
                          <span class="label label-success"> Finding # <%= finding.id %></span> | <%= finding.audit.department_name %> 


                         <% if finding.status_id == "CAPA Pending"  %>
                        <span class="label label-warning pull-right "> <%= finding.status_id %>  </span>
                         
                        <%elsif finding.status_id == "CAPA Submitted" %>    
                        <span class="label label-success pull-right"> <%= finding.status_id %> </span>
                  
                        <%elsif finding.risk_rating == "Closed" %>       
                        <span class="label label-info pull-right"> <%= finding.status_id %> </span>
                  
                        <%else %>        
                        <span class="label label-primary pull-right"> <%= finding.status_id %> </span>
                        <%end%>  
                    </div>
                    
                   <div class="panel-body" style="background:#ecf0f1">
                   <%= finding.description %>
                   </div>
                    
                  <div class="panel-footer" style="background:#ecf0f1">
                    
                    <%= link_to time_ago_in_words(finding.created_at) + " ago" , finding %>  |
                    
                    <span class="label label-warning"><%= finding.category %></span>         |
                    
                   <% if finding.risk_rating == "Critical"  %>
                   <span class="label label-danger "> 
                   <%= finding.risk_rating + " risk" %>
                   </span> 
                   <%elsif finding.risk_rating == "High" %>    
                   <span class="label label-warning"> 
                   <%= finding.risk_rating + " risk" %>
                   </span>
                   <%elsif finding.risk_rating == "Medium" %>    
                   <span class="label label-primary "> 
                   <%= finding.risk_rating + " risk" %>
                   </span>
                   <%elsif finding.risk_rating == "Low" %>        
                   <span class="label label-info "> 
                   <%= finding.risk_rating + " risk" %>
                   </span>
                   <%elsif finding.risk_rating == "No Risk" %>        
                   <span class="label label-default "> 
                   <%= finding.risk_rating + " risk" %>
                   </span>
                   <%else %>        
                   
                    <span class="label label-primary "> 
                    <%= finding.risk_rating + " risk" %>
                    </span> 
                    <%end%> 
                    
                    
                      
                   <span class="pull-right">
                     |
                     <strong> <a href="#"  data-id="<%= finding.id%>" data-toggle="modal" data-target="#myModal">  CAPA </a></strong>
                     |
                     <%#= hidden_field_tag :audit_id , params[:id] %>
                      <%= link_to 'Modify', edit_finding_path(finding,:audit_id => params[:id]) %> |
                   <%= link_to 'Destroy', finding_path(finding,:audit_id => params[:id]), method: :delete, data: { confirm: 'This action is permanent, are you sure?' } %>
                   </span>
                    
                    <br/><br/>
                    <p><% finding.documents.each do |document| %> <label class="badge">
                        <%= link_to document.attachment_file_name, document.attachment.url %>
                      </label> <%end%>  
                     
                  </div>  
                      
                  </div>
                    <div class="page-header"></div>
             </small>
               
             <% end %> 
             <% else %>
                    
                <div class="panel panel-default">
                <div class="panel-heading">
                 No findings. <%# = link_to " Create Finding", new_audit_finding_path(@audit.id), class: "btn btn-success btn-sm pull-right" %>
                
                </div>
               

        <%end%>
    
    
    </div>
    </div>
    </div>
      <div class="container">
<div class="col-lg-10 col-md-10 col-lg-offset-1">
    <div class="alert alert-warning fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Need your attention!</strong> Follow-up alerts will stop the moment you select "Findings submitted"
    </div>  
    </div>
        </div>
      
      
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Corrective and Preventive Action </h4>
      </div>
      <div class="modal-body">
       <!-- <input type="label" name="finding" id="finding" value="" /> -->
        <label id="finding"></label>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>   
 <script type"text/javascript">
  $(document).ready(function() {

  $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {

    var data_id = '';
  
    if (typeof $(this).data('id') !== 'undefined') {
  
      data_id = $(this).data('id');
      //alert(data_id);
    }
    $.ajax({
        type: "POST",
        dataType: "json",
        url: "find_capa?finding_id="+data_id,
      success: function(data){
       document.getElementById('finding').innerHTML = data ;
      },
    error: function(){
      document.getElementById('finding').innerHTML = "CAPA Missing Error" ;
  }
    }); 
   
  })
});    
</script>