config/routes.rb
AuditFace::Application.routes.draw do
  
  resources :reports

  resources :activities, only: [:index]

  devise_for :users 

  get "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_findings"
  resources :dashboards
  get "audits/export_findings"
  post "audits/export_findings"
  get "audits/share_schedule"
  post "audits/share_schedule"
  get "audits/find_capa"
  post "audits/find_capa"
  resources :audits do
  resources :findings
  
  end
 resources :findings
  resources :search

  
  root :to => "pages#landing"
  
  get "/pages/*id" => 'pages#show', as: :page, format: false
  get 'pages/landing' => 'high_voltage/pages#show', id: 'landing'

  get "/pages2/*id" => 'pages2#show', as: :page, format: false
  get 'pages2/landing2' => 'high_voltage/pages2#show', id: 'landing2'

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :report_name, :report_status, :report_tag
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>
<div class="container">
  
  <div class="col-lg-5 col-lg-offset-1">
  <div class="form-inputs">
    <select class="form-control">
  <option>--Select Audit--</option>
  <option>2</option>
  <option>3</option>
  <option>4</option>
  <option>5</option>
</select>
    <%= f.input :report_name %>
    <%= f.input :report_tag %>
    <%= f.input :report_status %>
  </div>
    
<label for="exampleInputFile">Upload report</label>
    <input type="file" id="exampleInputFile">
    <br/>
    
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
 
  </div> 
</div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div class="container">
   <div class="col-lg-10 col-lg-offset-1">
 <%= link_to 'New Report', new_report_path, class: "btn btn-default btn-sm" %>
  </div>
</div>
<br/>
<% @reports.each do |report| %>
<div class="container">
  
  <div class="col-lg-10 col-lg-offset-1">
    
    
    <div class="panel panel-default">
      <div class="panel-heading" style="background:#ecf0f1"> 
       
        Department name:  <%= report.report_name %> |
      Organization name:  <%= report.report_name %> |
        <label class="badge pull-right"><%= report.report_status %></label>
      </div>
      
 <div class="panel-body" style="background:#ecf0f1">
                    <strong style="color:#7f8c8d"> Report name:  <%= report.report_name %> </strong>
                   </div>
      
       <div class="panel-footer" style="background:#ecf0f1">
         <span><small>Created at: <%= report.created_at.strftime("%d-%b-%y") %> </small></span> | 
         <span ><small>Updated at: <%= report.updated_at.strftime("%d-%b-%y") %></small></span>
       <button type="button" class="btn btn-default btn-sm pull-right">Download audit report</button>
         <%= link_to 'Edit', edit_report_path(report), class: "btn btn-link btn-sm pull-right" %>
         <%= link_to 'Delete', report, method: :delete, data: { confirm: 'This would permanently delete the report' },  class: "btn btn-link btn-sm pull-right" %>
       <br/>
         <span class="label label-info"><%= report.report_tag %></span>
      </div>
</div>
</div>
</div>

<div class="page-header">
</div>
<% end %>

app/views/reports/new.html.erb
<!--<h1>New report</h1>-->

<%= render 'form' %>

<%# link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Report name:</b>
  <%= @report.report_name %>
</p>

<p>
  <b>Report tag:</b>
  <%= @report.report_tag %>
</p>

<p>
  <b>Report status:</b>
  <%= @report.report_status %>
</p>


<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>