config/routes.rb
AuditFace::Application.routes.draw do
  
  resources :reports

  resources :activities, only: [:index]

  devise_for :users 

  get "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_audits"
  post "dashboards/capa_pending_findings"
  resources :dashboards
  get "audits/export_findings"
  post "audits/export_findings"
  get "audits/share_schedule"
  post "audits/share_schedule"
  get "audits/find_capa"
  post "audits/find_capa"
  resources :audits do
  resources :findings
  
  end
 resources :findings
  resources :search

  
  root :to => "pages#landing"
  
  get "/pages/*id" => 'pages#show', as: :page, format: false
  get 'pages/landing' => 'high_voltage/pages#show', id: 'landing'

  get "/pages2/*id" => 'pages2#show', as: :page, format: false
  get 'pages2/landing2' => 'high_voltage/pages2#show', id: 'landing2'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # attr_accessible :title, :body
  
  belongs_to :user
  belongs_to :targetable, polymorphic: true
end

app/models/audit.rb
class Audit < ActiveRecord::Base
  attr_accessible :auditee_email, :auditee_name, :auditor_email, :auditor_name, :department_name, :end_date, :start_date, :user_id, :audit_type,:location, :secondry_auditor_name, :secondry_auditor_email
  belongs_to :user
  has_many :findings, :dependent => :destroy
  
  validates :department_name, :auditee_name, :auditee_email, :auditor_name, 
            :auditor_email, :location, :presence => true
            
  validates :start_date, :date => {:before_or_equal_to => :end_date, :message => 'must be before or same as end date' }
  
  self.per_page = 3

  validate :cannot_audit_self

  def cannot_audit_self
    self.errors[:base] << "You can not audit yourself." if self.auditee_email == self.auditor_email
  end
  def self.capa_pending_auto_follow_up
    @audits_capa_pending = []
    @audits = Audit.all
    @audits.each do |audit|
      audit.findings.each do |finding|
        if finding.status_id == "CAPA Pending" || finding.status_id == ""
          @audits_capa_pending << audit
          break
        end
      end
    end
    @audits_capa_pending.each do |audit|
      UserMailer.capa_pending_auto_follow_up(audit,current_user).deliver
    end
     #@user = User.all
     # @user.each do |u|
     #   UsersMailer.weekly_mail(u).deliver
    #end
  end
end

app/models/auditor.rb
class Auditor < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/document.rb
class Document < ActiveRecord::Base
 attr_accessible :attachment, :finding_id

 has_attached_file :attachment

 belongs_to :finding 
# accepts_nested_attributes_for :findings
include Rails.application.routes.url_helpers

  #def to_jq_upload
  #  {
  ##    "name" => read_attribute(:attachment_file_name),
   #   "size" => read_attribute(:attachment_file_size),
   #   "url" => upload.url(:original),
   #   "delete_url" => upload_path(self),
   #   "delete_type" => "DELETE" 
   # }
  #end
 #mount_uploader :attachment, AttachmentUploader
end

app/models/finding.rb
class Finding < ActiveRecord::Base
  attr_accessible :category, :corrective_action, :date_created, :description, 
                  :preventive_action, :risk_rating, :audit_id, :department_name, :category_name, 
                  :risk_name, :status_name, :status_id,
                  :documents_attributes, :iso_clause, :closure_date  #, :documents#,:avatar
  belongs_to :audit
  belongs_to :finding_type
  belongs_to :risk
  belongs_to :finding_status
  # belongs_to :document
   has_many :documents, :dependent => :destroy
  validates :closure_date, :date => {:after_or_equal_to => Time.now, :message => 'must be after or same as created date' }
  validates_presence_of :corrective_action, :if => Proc.new { |finding| finding.status_id == "Under review" || finding.status_id == "Closed"} ,:message => "Please enter CAPA before you change the status to Under Review"
#  has_attached_file :avatar #, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  
  accepts_nested_attributes_for :documents , :allow_destroy => true
  
end

app/models/finding_status.rb
class FindingStatus < ActiveRecord::Base
  attr_accessible :status_name, :string
  belongs_to :finding
end

app/models/finding_type.rb
class FindingType < ActiveRecord::Base
  attr_accessible :category_name
  belongs_to :finding
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :report_name, :report_status, :report_tag
end

app/models/risk.rb
class Risk < ActiveRecord::Base
  attr_accessible :risk_name
  belongs_to :finding
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_name,:mobile_number
  # attr_accessible :title, :body
  has_many :audits
  has_many :activities
  
  
  def gravatar_url
      
      stripped_email = email.strip
      downcased_email = stripped_email.downcase
      hash = Digest::MD5.hexdigest(downcased_email)
      
      "http://gravatar.com/avatar/#{hash}"
      
  end
  
  def create_activity(item, action)
      
      activity = activities.new
      activity.targetable = item
      
      activity.action = action
      activity.save
      activity
  
  end
  def self.weekly_update
      @user = User.all
      @user.each do |u|
        UsersMailer.weekly_mail(u).deliver
    end
  end
   private

    def send_welcome_email
      UserMailer.welcome_email(self).deliver
    end 
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_filter :authenticate_user!
  include HighVoltage::StaticPage

 def landing
   render :layout => 'landing'
  
  end 
  
  private

  def layout_for_page
    case params[:id]
    when 'landing'
      'landing'
    else
      'application'
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/findings_helper.rb
module FindingsHelper
end

app/helpers/pages2_helper.rb
module Pages2Helper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Audit management software, paperless audits, collaborative audits for auditors</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  
  <link href='https://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
  
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  
</head>

<style>
    
  .badge-success {
  background-color: #e74c3c;
  
}
  
</style>

<body style="padding-top:70px; font-family: 'Arial', sans-serif;">


  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background:#ffffff">
  <!-- Brand and toggle get grouped for better mobile display -->
  
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span class="navbar-brand" href="#" style="font-family: 'Montserrat', sans-serif;"> <span class="badge badge-success"><strong>77comply </strong></span><small> beta</small></span>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav" style="font-family: 'Open Sans', sans-serif; color:#ffffff; margin-left:50px;">
     <li><%= link_to ' Audits', audits_path %></li>
     <li><%= link_to ' Reports', reports_path %></li>
     <li><%= link_to ' Stats', dashboards_path %></li>
    
    </ul>
    
      
     <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
     
       <li><%= link_to (image_tag(current_user.gravatar_url, :size => "20x20")), edit_user_registration_path %></li> 
       <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
       
       <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        </ul>
    
      
      <div class="navbar-form navbar-right" role="search">
        
      <%= form_tag({:controller => 'search', :action => 'index'}, {:method => 'get'})  do |s| %>
        
      <div class="form-group">
        <div class="btn-group">
          <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
          Search by <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Audits</a></li>
        <li><a href="#">Findings</a></li>
        <li><a href="#">Reports</a></li>
    
        </ul>
        </div>
        <%= text_field_tag :search, params[:search], style: "width:200px; margin-top:5px", placeholder: "Jump to audits or findings", class: "input-sm" %>
        <%= submit_tag "Search", class: "btn btn-sm" %>
      </div>  
    <% end %>
    </div>
      
  </div><!-- /.navbar-collapse -->
</nav>

<div class="container">

<% if flash[:notice] %>

<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:notice] %>
</div>


<% end %>

<% if flash[:alert] %>

<div class="alert alert-warning alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:alert] %>
</div>


<% end %>

</div>
<br/>
<br/>
<%= yield %>





</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project management software exclusive to auditors</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
 
  <link href='https://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top:50px; font-family: 'Muli', sans-serif;">


<div class="container">

<% if flash[:notice] %>

<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:notice] %>
</div>


<% end %>

<% if flash[:alert] %>

<div class="alert alert-warning alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= flash[:alert] %>
</div>


<% end %>

</div>
<br/>
<br/>
<%= yield %>





</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Audit management software, paperless audits, collaborative audits for auditors</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
 
<link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="font-family: 'Open Sans', sans-serif">

  <div class="container">
    <h2 class="col-lg-offset-1" href="#" style="font-family: 'Montserrat', sans-serif; color: #e74c3c">77comply</h2>
    <%= link_to "Blog", "https://77comply.wordpress.com", :only_path => true, class: "pull-right" %>
    <a href="mailto:support@77comply.com" class="pull-right" style="margin-right:20px">Support </a>
    
  </div>
   <div class="container">
  <div class="page-header"></div>
  </div>   
     
  <div class="container">
   <div class="row-fluid">
     <div class="col-lg-12">
   <h2 class="col-lg-offset-3" href="#" style="font-family: 'Lato', sans-serif;">Your complete audit repository on a secured cloud </h2> 
   <a href="http://white-harbor-rails-62598.apse1.nitrousbox.com/users/sign_up" class="btn btn-danger btn-lg col-lg-offset-4" role="button" >Free till beta, Join now</a>
       <a href="http://white-harbor-rails-62598.apse1.nitrousbox.com/users/sign_in" class="btn btn-success btn-lg" role="button" >Sign in to your account</a>  
    
     </div>
    </div>
  </div>

  <div class="container">
  <div class="page-header"></div>
  </div> 

  <div class="container">
  <div class="row-fluid">
  
  <div class="col-lg-5 col-md-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("cloudsave.png", :alt => "Save audits on cloud", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">Paperless audit storage</h3>
  A Cloud enabled repository for all your audits and related data. All your audits are stored on secured cloud environment, now carry your audits wherever you travel.
  </div>
  </div>
  </div>  
  
  <div class="col-lg-5 col-md-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("aim.png", :alt => "Audit Insta add", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">Never miss an audit</h3>
  An inbuilt audit alert system to make sure you never miss an audit. An email notification system (SMS coming soon) ensures you stay ahead with your audit schedules
  </div> 
  </div>
  </div> 
    
  
  </div> <!-- end row -->
  </div> <!-- end container -->

  
  <div class="container">
  <div class="page-header"></div>
  </div> 

  <div class="container">
  <div class="row-fluid">
  
  <div class="col-lg-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("follow.png", :alt => "77comply InstaSearch", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">Auto follow-up</h3>
  Focus on audits that are in process and let 77comply follow-up with auditees to close the findings. A reminder is sent to auditee every week with pending actionables.
  </div>
  </div>
  </div>  
  
  <div class="col-lg-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("newreport.png", :alt => "Audit Insta add", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">Instant audit reports</h3>
 With one click generate a pdf copy (word format coming soon) with all the observations. Later tweak the report to your satisfaction and share.
  </div>
  </div>
  </div> 
    
  
  </div> <!-- end row -->
  </div> <!-- end container -->

  <div class="container">
  <div class="page-header"></div>
  </div> 

  <div class="container">
  <div class="row-fluid">
  
  <div class="col-lg-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("chart.png", :alt => "77comply InstaSearch", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">InstaDashboards</h3>
  Get instant information on audits, pending CAPA's, upcoming audits and open audits (greater than 30 days) all in one place.
  </div>
  </div>
  </div>  
  
  <div class="col-lg-5 col-lg-offset-1">
    
  <div class="media">
  <a class="pull-left" href="#">
  <%= image_tag("alert1.png", :alt => "Instant alerts", :width => '96') %>
  </a>
  <div class="media-body">
  <h3 class="media-heading">InstaAlerts</h3>
  Get email alerts on weekly status, audit creations and closures. Sms Alerts (Coming Soon)
  </div>
  </div>
  </div> 
    
  
  </div> <!-- end row -->
  </div> <!-- end container -->  
  
<div class="container">


<br/>
<br/>
<%= yield %>
</div>
  
   <div class="page-header"></div>
   <div class="container">
     <h1 class="col-lg-offset-4" style="font-family: 'Lato', sans-serif;"> Who uses 77comply?   </h1> 
     <div class="col-lg-5">
     <div class="well">
       <ul >
       <li><h4>Internal Auditors</h4></li>
       <li><h4>Independent Auditors</h4></li>
        <li><h4>Quality Managers</h4></li>
         </ul>
       </div>
       </div>
    <div class="col-lg-5 col-lg-offset-2">
      <div class="well">
     <ul >
       <li><h4>Lead Auditors</h4></li>
       <li><h4>Management Representatives</h4></li>
       <li><h4>Consultants</h4></li>
     </ul>
   </div>
       </div>
  </div>
  <div class="page-header"></div>
  

   <div class="container">
     <h1 class="col-lg-offset-4" style="font-family: 'Lato', sans-serif;">Conduct range of audits   </h1> 
     <div class="col-lg-5">
        <div class="well">
     <ul >
       <li><h4>ISO audits</h4></li>
       <li><h4>Process or performance audits</h4></li>
        <li><h4>Risk based audits</h4></li>
         </ul> 
               </div>
       </div>
    <div class="col-lg-5 col-lg-offset-2">
        <div class="well">
     <ul >
       <li><h4>Statutory audits</h4></li>
       <li><h4>Vendor or supplier audits</h4></li>
       <li><h4>Second or Third party</h4></li>
     </ul>
          </div>
   </div>
  </div>
  <div class="page-header"></div>
    <div id="footer">
      <div class="container">
        <p class="text-muted credit col-lg-offset-5">Made in India with love by <a href="http://16columns.wordpress.com/">16columns</a>. | 
          <%= link_to(image_tag("twitter.png", :alt => "logo", :title => "https://twitter.com/77comply", size: "48x48"), "https://twitter.com/77comply",) %> </p>
      </div>
    </div>



</body>
</html>

app/views/layouts/landing2.html.erb
hello world